package com.example.core.localization

data class AppStrings(
  val appTitle: String,
  val appSubtitle: String,
  val bismillah: String,
  val startPlaying: String,
  val welcomeBack: String,
  val currentLevel: String,
  val streakDays: String,
  val coins: String,
  val xp: String,
  val playNow: String,
  val dailyRewardTitle: String,
  val dailyRewardAvailable: String,
  val claimReward: String,
  val claimed: String,

  // Modes
  val quickChallenge: String,
  val quickChallengeDesc: String,
  val dailyChallenge: String,
  val dailyChallengeDesc: String,
  val categoryChallenge: String,
  val categoryChallengeDesc: String,
  val timeChallenge: String,
  val timeChallengeDesc: String,
  val survivalMode: String,
  val survivalModeDesc: String,
  val levelMode: String,
  val levelModeDesc: String,
  val practiceMode: String,
  val practiceModeDesc: String,

  // Categories
  val catQuran: String,
  val catQuranDesc: String,
  val catSeerah: String,
  val catSeerahDesc: String,
  val catProphets: String,
  val catProphetsDesc: String,
  val catWorship: String,
  val catWorshipDesc: String,
  val catRamadan: String,
  val catRamadanDesc: String,
  val catAdhkar: String,
  val catAdhkarDesc: String,
  val catManners: String,
  val catMannersDesc: String,
  val catGeneral: String,
  val catGeneralDesc: String,

  // Quiz UI
  val questionProgress: String,
  val questionScore: String,
  val timerSeconds: String,
  val correctAlert: String,
  val incorrectAlert: String,
  val nextQuestion: String,
  val finishQuiz: String,
  val explanation: String,
  val source: String,
  val hintDialogTitle: String,
  val noHintAvailable: String,
  val gotIt: String,
  val outOfLifelines: String,
  val lifelineUsed: String,

  // Lifelines
  val lifeline5050: String,
  val lifelineHint: String,
  val lifelineTime: String,
  val lifelineSkip: String,

  // Results UI
  val challengeComplete: String,
  val quizSummary: String,
  val finalScore: String,
  val accuracy: String,
  val correctAnswers: String,
  val wrongAnswers: String,
  val totalXpGained: String,
  val totalCoinsGained: String,
  val playAgain: String,
  val returnHome: String,
  val chooseCategory: String,
  val levelUpTitle: String,

  // Profile & Stats
  val profileTitle: String,
  val statisticsTitle: String,
  val totalGames: String,
  val totalQuestions: String,
  val longestStreak: String,
  val bestScore: String,
  val achievementsTitle: String,
  val unlocked: String,
  val locked: String,

  // Settings
  val settingsTitle: String,
  val language: String,
  val soundEffects: String,
  val soundVolume: String,
  val backgroundMusic: String,
  val vibration: String,
  val darkMode: String,
  val themeModeSystem: String,
  val themeModeLight: String,
  val themeModeDark: String,
  val contentSafetyNotice: String,
  val contentSafetyDesc: String,
  val aboutApp: String,
  val version: String,
  val credits: String,
  val creditsDesc: String,
  val resetProgress: String,
  val resetConfirmTitle: String,
  val resetConfirmDesc: String,
  val cancel: String,
  val confirm: String,

  // Pause & Exit Dialog
  val pauseTitle: String,
  val resumeGame: String,
  val restartRound: String,
  val exitQuiz: String,
  val exitConfirmTitle: String,
  val exitConfirmDesc: String,
  val timeUpAlert: String,
  val newAchievementUnlocked: String,

  // Onboarding
  val onbTitle1: String,
  val onbDesc1: String,
  val onbTitle2: String,
  val onbDesc2: String,
  val onbTitle3: String,
  val onbDesc3: String,
  val getStarted: String,
  val skip: String
)

object LocalizationManager {
  val English = AppStrings(
    appTitle = "Islamic Challenge",
    appSubtitle = "Expand your knowledge in faith & wisdom",
    bismillah = "In the Name of Allah, the Most Gracious, the Most Merciful",
    startPlaying = "Begin Challenge",
    welcomeBack = "As-salamu alaykum",
    currentLevel = "Level",
    streakDays = "Day Streak",
    coins = "Coins",
    xp = "XP",
    playNow = "Play Now",
    dailyRewardTitle = "Daily Reward",
    dailyRewardAvailable = "Reward Ready!",
    claimReward = "Claim Reward",
    claimed = "Claimed",

    quickChallenge = "Quick Challenge",
    quickChallengeDesc = "10 random questions across all categories",
    dailyChallenge = "Daily Challenge",
    dailyChallengeDesc = "Today's curated questions with streak bonuses",
    categoryChallenge = "Category Challenge",
    categoryChallengeDesc = "Master your choice of Islamic knowledge",
    timeChallenge = "Time Challenge",
    timeChallengeDesc = "Race against the clock in 60 rapid seconds",
    survivalMode = "Survival Mode",
    survivalModeDesc = "One life: how far can your knowledge reach?",
    levelMode = "Level Mode",
    levelModeDesc = "Progress from Beginner to Advanced Learner",
    practiceMode = "Practice Mode",
    practiceModeDesc = "Relaxed untimed learning with instant answers",

    catQuran = "Holy Quran",
    catQuranDesc = "Surahs, Ayahs, revelation history & facts",
    catSeerah = "Prophetic Seerah",
    catSeerahDesc = "Life of Prophet Muhammad ﷺ & companions",
    catProphets = "Stories of Prophets",
    catProphetsDesc = "Prophets in Quran, their miracles & nations",
    catWorship = "Worship & Fiqh",
    catWorshipDesc = "Salah, Wudu, Zakat, Fasting & Hajj",
    catRamadan = "Ramadan & Fasting",
    catRamadanDesc = "Suhoor, Iftar, Laylat al-Qadr & etiquette",
    catAdhkar = "Adhkar & Duas",
    catAdhkarDesc = "Morning, evening & daily supplications",
    catManners = "Islamic Manners",
    catMannersDesc = "Parents, kindness, honesty & good conduct",
    catGeneral = "General Knowledge",
    catGeneralDesc = "Islamic history, geography & landmarks",

    questionProgress = "Question",
    questionScore = "Score",
    timerSeconds = "s",
    correctAlert = "Correct! Masha'Allah",
    incorrectAlert = "Not quite. Learn from this:",
    nextQuestion = "Continue",
    finishQuiz = "Finish Quiz",
    explanation = "Explanation",
    source = "Source / Reference",
    hintDialogTitle = "Helpful Clue",
    noHintAvailable = "Reflect upon the question carefully.",
    gotIt = "Understood",
    outOfLifelines = "No lifelines remaining of this type",
    lifelineUsed = "Lifeline activated!",

    lifeline5050 = "50 / 50",
    lifelineHint = "Hint",
    lifelineTime = "+15s",
    lifelineSkip = "Skip",

    challengeComplete = "Challenge Completed!",
    quizSummary = "Quiz Summary",
    finalScore = "Final Score",
    accuracy = "Accuracy",
    correctAnswers = "Correct",
    wrongAnswers = "Incorrect",
    totalXpGained = "XP Earned",
    totalCoinsGained = "Coins Earned",
    playAgain = "Play Again",
    returnHome = "Back to Home",
    chooseCategory = "Categories",
    levelUpTitle = "Level Up! Congratulations",

    profileTitle = "My Profile",
    statisticsTitle = "Statistics",
    totalGames = "Total Games",
    totalQuestions = "Questions Answered",
    longestStreak = "Longest Streak",
    bestScore = "Highest Score",
    achievementsTitle = "Achievements & Badges",
    unlocked = "Unlocked",
    locked = "Locked",

    settingsTitle = "Settings",
    language = "Language",
    soundEffects = "Sound Effects",
    soundVolume = "Sound Volume",
    backgroundMusic = "Background Music",
    vibration = "Haptic Vibration",
    darkMode = "Theme Mode",
    themeModeSystem = "System Default",
    themeModeLight = "Light Theme",
    themeModeDark = "Dark Theme",
    contentSafetyNotice = "Content & Religious Accuracy",
    contentSafetyDesc = "Questions and sources have been carefully authored based on uncontested Islamic facts and verified references.",
    aboutApp = "About Islamic Challenge",
    version = "Version 1.0.0 (Native Android & Compose)",
    credits = "Authentic Scholarly References",
    creditsDesc = "Quranic verses (Hafs 'an 'Asim), Sahih al-Bukhari, Sahih Muslim, Riyadh as-Salihin, and established prophetic biographies.",
    resetProgress = "Reset Game Progress",
    resetConfirmTitle = "Reset All Progress?",
    resetConfirmDesc = "This will reset all your coins, XP, streaks, and achievements. This cannot be undone.",
    cancel = "Cancel",
    confirm = "Reset",

    pauseTitle = "Game Paused",
    resumeGame = "Resume",
    restartRound = "Restart Round",
    exitQuiz = "Exit Quiz",
    exitConfirmTitle = "Exit Challenge?",
    exitConfirmDesc = "Are you sure you want to exit? Your answered questions will be saved to your progress.",
    timeUpAlert = "Time's Up!",
    newAchievementUnlocked = "🏆 Achievement Unlocked!",

    onbTitle1 = "Sacred Knowledge at Your Fingertips",
    onbDesc1 = "Explore questions on the Holy Quran, Seerah, Prophets, Worship, Ramadan, and daily Adhkar in a dignified experience.",
    onbTitle2 = "Earn XP, Badges & Streaks",
    onbDesc2 = "Maintain your daily streak, unlock respectful milestones, and advance through progressive learning tiers.",
    onbTitle3 = "Lifelines & Rewarding Challenges",
    onbDesc3 = "Use 50/50, Hints, and Extra Time assists to learn calmly with verified authentic explanations.",
    getStarted = "Start Journey",
    skip = "Skip"
  )

  val Arabic = AppStrings(
    appTitle = "تحدي المعرفة الإسلامية",
    appSubtitle = "طوّر معرفتك في رحاب الإيمان والحكمة",
    bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    startPlaying = "ابدأ التحدي",
    welcomeBack = "السلام عليكم ورحمة الله",
    currentLevel = "المستوى",
    streakDays = "أيام الحماس",
    coins = "النقاط الذهبية",
    xp = "نقاط الخبرة",
    playNow = "العب الآن",
    dailyRewardTitle = "المكافأة اليومية",
    dailyRewardAvailable = "مكافأتك جاهزة!",
    claimReward = "استلام المكافأة",
    claimed = "تم الاستلام",

    quickChallenge = "التحدي السريع",
    quickChallengeDesc = "١٠ أسئلة متنوعة من شتى أبواب المعرفة",
    dailyChallenge = "التحدي اليومي",
    dailyChallengeDesc = "أسئلة اليوم المتجددة مع مكافأة الحماس اليومي",
    categoryChallenge = "تحدي الأقسام",
    categoryChallengeDesc = "اختر باباً وتعمّق في مسائله المباركة",
    timeChallenge = "تحدي الوقت",
    timeChallengeDesc = "أجب عن أكبر قدر من الأسئلة في ٦٠ ثانية",
    survivalMode = "تحدي الثبات",
    survivalModeDesc = "فرصة واحدة: كم سؤالاً متواصلاً ستجيب؟",
    levelMode = "تحدي المستويات",
    levelModeDesc = "تدرج من طالب مبتدئ إلى باحث متقدم",
    practiceMode = "نمط التعلّم والتكرار",
    practiceModeDesc = "تعلّم هادئ بلا وقت ولا خسارة مع الشرح الفوري",

    catQuran = "القرآن الكريم",
    catQuranDesc = "السور، الآيات، المكي والمدني، ولطائف التنزيل",
    catSeerah = "السيرة النبوية",
    catSeerahDesc = "سيرة النبي المصطفى ﷺ، أصحابه، والهجرة",
    catProphets = "قصص الأنبياء",
    catProphetsDesc = "أنبياء الله في القرآن، معجزاتهم وأقوامهم",
    catWorship = "العبادات والفقه",
    catWorshipDesc = "الصلاة، الطهارة، الزكاة، الصوم، والحج",
    catRamadan = "رمضان المبارك",
    catRamadanDesc = "الصيام، السحور، الإفطار، وليلة القدر",
    catAdhkar = "الأذكار والأدعية",
    catAdhkarDesc = "أذكار الصباح والمساء وأدعية اليوم والليلة",
    catManners = "الآداب والأخلاق",
    catMannersDesc = "بر الوالدين، حسن الجوار، الصدق، والأمانة",
    catGeneral = "معارف عامة",
    catGeneralDesc = "تاريخ إسلامي ومعالم وحضارة إسلامية",

    questionProgress = "السؤال",
    questionScore = "النقاط",
    timerSeconds = "ث",
    correctAlert = "أحسنت! إجابة صحيحة ما شاء الله",
    incorrectAlert = "ليست الإجابة الصحيحة. تعلّم من هذا التوضيح:",
    nextQuestion = "المتابعة",
    finishQuiz = "إنهاء التحدي",
    explanation = "التوضيح والمعلومة",
    source = "المصدر / المرجع",
    hintDialogTitle = "تلميح مساعد",
    noHintAvailable = "تأمل في صيغة السؤال جيداً.",
    gotIt = "فهمت",
    outOfLifelines = "نفدت وسائل المساعدة من هذا النوع",
    lifelineUsed = "تم تفعيل وسيلة المساعدة!",

    lifeline5050 = "٥٠ / ٥٠",
    lifelineHint = "تلميح",
    lifelineTime = "+١٥ث",
    lifelineSkip = "تخطي",

    challengeComplete = "اكتمل التحدي بنجاح!",
    quizSummary = "ملخص الجولة",
    finalScore = "النتيجة النهائية",
    accuracy = "نسبة الدقة",
    correctAnswers = "إجابات صحيحة",
    wrongAnswers = "إجابات خاطئة",
    totalXpGained = "الخبرة المكتسبة",
    totalCoinsGained = "الذهب المكتسب",
    playAgain = "إعادة التحدي",
    returnHome = "الرئيسية",
    chooseCategory = "الأقسام",
    levelUpTitle = "مبارك! ارتقيت لمستوى جديد",

    profileTitle = "الملف الشخصي",
    statisticsTitle = "الإحصائيات",
    totalGames = "إجمالي التحديات",
    totalQuestions = "الأسئلة المجابة",
    longestStreak = "أطول حماس متواصل",
    bestScore = "أعلى نتيجة",
    achievementsTitle = "الأوسمة والإنجازات",
    unlocked = "مكتمل",
    locked = "مغلق",

    settingsTitle = "الإعدادات",
    language = "اللغة",
    soundEffects = "المؤثرات الصوتية",
    soundVolume = "مستوى الصوت",
    backgroundMusic = "الموسيقى الخلفية الهادئة",
    vibration = "الاهتزاز التفاعلي",
    darkMode = "مظهر التطبيق",
    themeModeSystem = "تلقائي (حسب النظام)",
    themeModeLight = "المظهر الفاتح",
    themeModeDark = "المظهر الداكن",
    contentSafetyNotice = "سلامة المحتوى والتدقيق",
    contentSafetyDesc = "صيغت الأسئلة والشروحات بعناية استناداً إلى الحقائق الإسلامية الثابتة والمراجع الموثوقة دون خوض في الخلافيات.",
    aboutApp = "عن تطبيق تحدي المعرفة",
    version = "الإصدار 1.0.0 (أندرويد أصيل وCompose)",
    credits = "المراجع الإسلامية المعتمدة",
    creditsDesc = "آيات الذكر الحكيم (رواية حفص عن عاصم)، صحيح البخاري، صحيح مسلم، رياض الصالحين، وأمهات كتب السيرة النبوية.",
    resetProgress = "إعادة ضبط التقدم",
    resetConfirmTitle = "هل تريد تصفير التقدم؟",
    resetConfirmDesc = "سيؤدي هذا إلى تصفير نقاطك، أوسمتك، ومستواك. لا يمكن التراجع عن هذا الإجراء.",
    cancel = "إلغاء",
    confirm = "تأكيد التصفير",

    pauseTitle = "متوقف مؤقتًا",
    resumeGame = "استمرار التحدي",
    restartRound = "إعادة الجولة",
    exitQuiz = "الخروج من الجولة",
    exitConfirmTitle = "تأكيد الخروج",
    exitConfirmDesc = "هل أنت متأكد من رغبتك في الخروج؟ سيتم حفظ الأسئلة التي أجبت عليها.",
    timeUpAlert = "انتهى الوقت!",
    newAchievementUnlocked = "🏆 إنجاز جديد مبارك!",

    onbTitle1 = "علم نافع وتجربة كريمة",
    onbDesc1 = "أسئلة موثوقة في كتاب الله وسنة نبيه ﷺ وعباداتك وآدابك في واجهة إسلامية راقية.",
    onbTitle2 = "أوسمة وحماس يومي مستمر",
    onbDesc2 = "حافظ على حماسك اليومي، وارتق في مدارج طلب العلم واكسب أوسمة الإتقان.",
    onbTitle3 = "وسائل مساعدة وشروح تعليمية",
    onbDesc3 = "استعن بحذف إجابتين والتلميحات، وتعرّف على شرح كل مسألة مع مصدرها الصحيح.",
    getStarted = "ابدأ الرحلة المباركة",
    skip = "تخطي"
  )

  fun get(lang: AppLanguage): AppStrings = when (lang) {
    AppLanguage.ENGLISH -> English
    AppLanguage.ARABIC -> Arabic
  }
}
